name: Server deploy workflow
run-name: Server deploy run
on:
  push:
    paths:
      - 'Server/**'
    branches:
    - main
jobs:
  server-deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          first_ssh: |
            ./update.sh
